# Description: MariaDB Dockerfile

# pull base image
FROM debian:bullseye

# update and upgrade the system
RUN apt-get update && apt-get upgrade -y

# # install the required packages
RUN apt-get install -y mariadb-server

# copy file from host to container
COPY ./tools/mdb-conf.sh /mdb-conf.sh

# set permissions to the file
RUN chmod +x /mdb-conf.sh

EXPOSE 3306

# define entrypoint command to run when the container starts
ENTRYPOINT ["./mdb-conf.sh"]
