# the services part
services:
#mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
#nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

#bonus part
  static_site:
    container_name: node
    build: ./srcs/requirements/bonus/node_server
    ports:
      - '1337:1337'
    restart: always
  
  redis:
    container_name: redis
    build: ./srcs/requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  ftp-server:
    build: ./srcs/requirements/bonus/ftp_server
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress:/var/www/html"
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer
    build: ./srcs/requirements/bonus/adminer
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - inception
    restart: always

  cadvisor:
    container_name: cadvisor
    build: ./srcs/requirements/bonus/cadvisor/.
    image: cadvisor:42
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro,rslave
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro,rslave  
    restart: always

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/data/wordpress
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception
